[package]
name = "rasterize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "^0.2"
# png = "^0.17"
sdl2 = "^0.34"
glam = "^0.18"


[profile.release]
debug = true
